import type { PlatformAgentRole, VerticalId } from '@/lib/ai-agents/types'

export type AgentStatus = 'active' | 'paused' | 'testing' | 'draft'
export type AgentAction = 'budget_increase' | 'budget_decrease' | 'pause_ad' | 'launch_ad' | 'reallocate' | 'creative_swap'
export type ApprovalStatus = 'pending' | 'approved' | 'rejected' | 'auto_approved'

export interface AgentRecommendation {
  id: string
  agentId: string
  agentName: string
  action: AgentAction
  title: string
  rationale: string
  confidence: number // 0-1
  estimatedImpactUsd: number
  campaignName: string
  createdAt: string // ISO
  approvalStatus: ApprovalStatus
}

export interface MyAgent {
  id: string
  name: string
  role: PlatformAgentRole | 'custom'
  vertical: VerticalId
  status: AgentStatus
  source: 'platform' | 'rented' | 'self_made'
  /** ISO timestamp when this agent was rented/created. */
  startedAt: string
  /** Total recommendations made. */
  recommendationsCount: number
  /** Number of approved recommendations. */
  approvedCount: number
  /** Estimated savings/profit in USD generated by this agent's actions. */
  impactUsd: number
  /** Whether this agent has auto-approval enabled (high-confidence only). */
  autoApprove: boolean
  /** Monthly cost (rented only). */
  monthlyCostUsd?: number
  /** Avatar emoji */
  emoji: string
  /** Brand color */
  accent: string
  /** Recent recommendations (preview). */
  recent: AgentRecommendation[]
}

export interface StoreAgent {
  id: string
  name: string
  author: string
  authorAvatar: string
  vertical: VerticalId
  description: string
  priceMonthlyUsd: number
  pricePerActionUsd?: number
  status: 'testing' | 'published'
  testDaysRemaining?: number
  /** Public stats */
  rentersCount: number
  avgRoasMultiplier: number
  rating: number // 1-5
  reviewsCount: number
  tags: string[]
  emoji: string
  accent: string
}

export const VERTICAL_LABELS_AGENTS: Record<VerticalId, string> = {
  ecommerce: 'E-commerce',
  course: 'Kurs / Ta\'lim',
  restaurant: 'Restoran / Lokal',
}

export const ACTION_LABELS: Record<AgentAction, { title: string; emoji: string; color: string }> = {
  budget_increase: { title: 'Byudjet oshirish', emoji: '📈', color: '#16a34a' },
  budget_decrease: { title: 'Byudjet kamaytirish', emoji: '📉', color: '#dc2626' },
  pause_ad: { title: "Reklamani pauza", emoji: '⏸️', color: '#ea580c' },
  launch_ad: { title: 'Yangi reklama', emoji: '🚀', color: '#0284c7' },
  reallocate: { title: 'Qayta taqsim', emoji: '🔄', color: '#7c3aed' },
  creative_swap: { title: 'Kreativ almashtirish', emoji: '🎨', color: '#db2777' },
}

export const STATUS_LABELS: Record<AgentStatus, { title: string; color: string; bg: string }> = {
  active: { title: 'Aktiv', color: '#15803d', bg: 'bg-emerald-100 dark:bg-emerald-500/20' },
  paused: { title: "To'xtatilgan", color: '#a16207', bg: 'bg-amber-100 dark:bg-amber-500/20' },
  testing: { title: 'Sinov rejimida', color: '#1d4ed8', bg: 'bg-blue-100 dark:bg-blue-500/20' },
  draft: { title: 'Qoralama', color: '#6b7280', bg: 'bg-slate-100 dark:bg-slate-500/20' },
}

const NOW = Date.now()

function isoMinutesAgo(min: number): string {
  return new Date(NOW - min * 60_000).toISOString()
}

function isoDaysAgo(days: number): string {
  return new Date(NOW - days * 86_400_000).toISOString()
}

export const DEMO_MY_AGENTS: MyAgent[] = [
  {
    id: 'my_001',
    name: 'Media Buyer Pro',
    role: 'media_buyer',
    vertical: 'ecommerce',
    status: 'active',
    source: 'platform',
    startedAt: isoDaysAgo(45),
    recommendationsCount: 87,
    approvedCount: 73,
    impactUsd: 2_840,
    autoApprove: false,
    emoji: '📊',
    accent: '#0284c7',
    recent: [
      {
        id: 'rec_001',
        agentId: 'my_001',
        agentName: 'Media Buyer Pro',
        action: 'budget_increase',
        title: 'Krossovka kampaniyasi byudjetini +25%',
        rationale: 'ROAS 4.2x — eng yuqori, scale qilish vaqti',
        confidence: 0.92,
        estimatedImpactUsd: 320,
        campaignName: 'Krossovka — Meta 2026 Q1',
        createdAt: isoMinutesAgo(12),
        approvalStatus: 'pending',
      },
      {
        id: 'rec_002',
        agentId: 'my_001',
        agentName: 'Media Buyer Pro',
        action: 'pause_ad',
        title: 'Lookalike 1% — pauza qilish',
        rationale: 'CPA $14, target $8. 7 kunda 12 ta lead — kam',
        confidence: 0.85,
        estimatedImpactUsd: 180,
        campaignName: 'Krossovka — Meta 2026 Q1',
        createdAt: isoMinutesAgo(48),
        approvalStatus: 'pending',
      },
    ],
  },
  {
    id: 'my_002',
    name: 'Creative Studio AI',
    role: 'creative',
    vertical: 'ecommerce',
    status: 'active',
    source: 'platform',
    startedAt: isoDaysAgo(45),
    recommendationsCount: 34,
    approvedCount: 28,
    impactUsd: 1_120,
    autoApprove: false,
    emoji: '🎨',
    accent: '#db2777',
    recent: [
      {
        id: 'rec_003',
        agentId: 'my_002',
        agentName: 'Creative Studio AI',
        action: 'creative_swap',
        title: '9:16 video reels — Tashkent shahar bo\'yicha',
        rationale: 'Reels engagement 3x yuqori, lokal kontekst yaxshi ishlaydi',
        confidence: 0.88,
        estimatedImpactUsd: 240,
        campaignName: 'Krossovka — Meta 2026 Q1',
        createdAt: isoMinutesAgo(120),
        approvalStatus: 'pending',
      },
    ],
  },
  {
    id: 'my_003',
    name: 'Analyst Bot',
    role: 'analyst',
    vertical: 'ecommerce',
    status: 'active',
    source: 'platform',
    startedAt: isoDaysAgo(45),
    recommendationsCount: 56,
    approvedCount: 51,
    impactUsd: 890,
    autoApprove: true,
    emoji: '🔍',
    accent: '#7c3aed',
    recent: [
      {
        id: 'rec_004',
        agentId: 'my_003',
        agentName: 'Analyst Bot',
        action: 'reallocate',
        title: 'Hafta hisoboti — 5 ta anomaliya topildi',
        rationale: 'CTR pasayish, CPM yuqori — Yandex kanalida sifat past',
        confidence: 0.95,
        estimatedImpactUsd: 150,
        campaignName: 'Umumiy hisobot',
        createdAt: isoMinutesAgo(360),
        approvalStatus: 'auto_approved',
      },
    ],
  },
  {
    id: 'my_004',
    name: 'Asaxiy SuperLookalike',
    role: 'custom',
    vertical: 'ecommerce',
    status: 'testing',
    source: 'rented',
    monthlyCostUsd: 39,
    startedAt: isoDaysAgo(8),
    recommendationsCount: 12,
    approvedCount: 9,
    impactUsd: 320,
    autoApprove: false,
    emoji: '🎯',
    accent: '#16a34a',
    recent: [],
  },
]

export const DEMO_STORE_AGENTS: StoreAgent[] = [
  {
    id: 'store_001',
    name: 'Asaxiy SuperLookalike v3',
    author: 'Dilshod Tursunov',
    authorAvatar: '👨‍💻',
    vertical: 'ecommerce',
    description: "O'zbek e-commerce uchun super lookalike modeli. Asaxiy.uz da 6 oy o'rganildi.",
    priceMonthlyUsd: 39,
    pricePerActionUsd: 0.08,
    status: 'published',
    rentersCount: 47,
    avgRoasMultiplier: 3.4,
    rating: 4.8,
    reviewsCount: 32,
    tags: ['Lookalike', 'E-commerce', 'UZ'],
    emoji: '🎯',
    accent: '#16a34a',
  },
  {
    id: 'store_002',
    name: 'Restoran Geo Hunter',
    author: 'Sevara Karimova',
    authorAvatar: '👩‍🍳',
    vertical: 'restaurant',
    description: '500-2km radiusda mijozlarni topadi. Tashkent restoranlarida sinovdan o\'tgan.',
    priceMonthlyUsd: 19,
    status: 'published',
    rentersCount: 23,
    avgRoasMultiplier: 2.8,
    rating: 4.6,
    reviewsCount: 18,
    tags: ['Geo', 'Restoran', 'Local'],
    emoji: '🍔',
    accent: '#ea580c',
  },
  {
    id: 'store_003',
    name: 'Kurs Funnel Master',
    author: 'Akmal Yuldashev',
    authorAvatar: '👨‍🏫',
    vertical: 'course',
    description: 'Onlayn kurs uchun lead-form + remarketing strategiyasi. 3 hafta sinov.',
    priceMonthlyUsd: 0,
    pricePerActionUsd: 0.12,
    status: 'testing',
    testDaysRemaining: 11,
    rentersCount: 8,
    avgRoasMultiplier: 2.1,
    rating: 4.4,
    reviewsCount: 5,
    tags: ['Lead', 'Kurs', 'Funnel'],
    emoji: '🎓',
    accent: '#7c3aed',
  },
  {
    id: 'store_004',
    name: 'Sale Surge Detector',
    author: 'Aziz Rahimov',
    authorAvatar: '🧑‍💼',
    vertical: 'ecommerce',
    description: "Aktsiya kunlari va vaqtli sotuvlarda byudjetni avtomatik oshiradi.",
    priceMonthlyUsd: 29,
    status: 'published',
    rentersCount: 31,
    avgRoasMultiplier: 3.1,
    rating: 4.7,
    reviewsCount: 22,
    tags: ['Pacing', 'E-commerce', 'Auto'],
    emoji: '⚡',
    accent: '#0284c7',
  },
  {
    id: 'store_005',
    name: 'Reels Creative Riser',
    author: 'Nigora Sodiqova',
    authorAvatar: '👩‍🎨',
    vertical: 'ecommerce',
    description: 'Instagram Reels formatida kreativlar generatsiyasi va A/B test.',
    priceMonthlyUsd: 45,
    status: 'published',
    rentersCount: 38,
    avgRoasMultiplier: 2.9,
    rating: 4.5,
    reviewsCount: 27,
    tags: ['Reels', 'Creative', 'A/B'],
    emoji: '🎬',
    accent: '#db2777',
  },
  {
    id: 'store_006',
    name: 'Telegram Channel Bridger',
    author: 'Bekzod Tashpulatov',
    authorAvatar: '🧑‍💻',
    vertical: 'ecommerce',
    description: 'Meta auditoriyasini Telegram kanaliga olib o\'tadi. Channel + bot connector.',
    priceMonthlyUsd: 24,
    status: 'published',
    rentersCount: 19,
    avgRoasMultiplier: 2.5,
    rating: 4.3,
    reviewsCount: 14,
    tags: ['Telegram', 'Cross-channel'],
    emoji: '✈️',
    accent: '#0ea5e9',
  },
]

/** All pending recommendations across active agents — for runtime dashboard. */
export function getPendingRecommendations(): AgentRecommendation[] {
  return DEMO_MY_AGENTS.flatMap((a) => a.recent).filter(
    (r) => r.approvalStatus === 'pending',
  )
}

/** Cumulative impact across all agents. */
export function getTotalImpactUsd(): number {
  return DEMO_MY_AGENTS.reduce((sum, a) => sum + a.impactUsd, 0)
}

/** Total approval rate. */
export function getApprovalRate(): number {
  const total = DEMO_MY_AGENTS.reduce((s, a) => s + a.recommendationsCount, 0)
  const approved = DEMO_MY_AGENTS.reduce((s, a) => s + a.approvedCount, 0)
  if (total === 0) return 0
  return Math.round((approved / total) * 100)
}

export function formatRelativeTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime()
  const min = Math.floor(diff / 60_000)
  if (min < 1) return 'hozirgina'
  if (min < 60) return `${min} daqiqa oldin`
  const hr = Math.floor(min / 60)
  if (hr < 24) return `${hr} soat oldin`
  const days = Math.floor(hr / 24)
  if (days < 7) return `${days} kun oldin`
  return new Date(iso).toLocaleDateString('uz-UZ')
}
