import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm'

/**
 * Creative ads generated by Creative Hub
 * Stores images, videos, and templates created by AI or users
 */
@Entity('creatives')
@Index(['workspaceId', 'createdAt'])
@Index(['campaignId'])
@Index(['type'])
@Index(['createdBy'])
export class Creative {
  @PrimaryGeneratedColumn('uuid')
  id: string

  /**
   * Workspace ID for multi-tenancy
   */
  @Column()
  @Index()
  workspaceId: string

  /**
   * Optional campaign link
   */
  @Column({ nullable: true })
  @Index()
  campaignId: string

  /**
   * Creative type
   */
  @Column({
    type: 'enum',
    enum: ['image', 'video', 'text-to-image', 'ugc'],
  })
  type: 'image' | 'video' | 'text-to-image' | 'ugc'

  /**
   * User who created creative
   */
  @Column()
  createdBy: string

  /**
   * Original prompt/input
   */
  @Column('text')
  prompt: string

  /**
   * Generated URL for single image
   */
  @Column({ nullable: true })
  generatedUrl: string

  /**
   * Multiple generated URLs for images/videos
   */
  @Column('jsonb', { nullable: true, default: () => "'[]'" })
  generatedUrls: string[]

  /**
   * Headline for the creative
   */
  @Column({ nullable: true })
  headline: string

  /**
   * Copy text
   */
  @Column('text', { nullable: true })
  copy: string

  /**
   * Creative metadata (style, aspect ratio, etc)
   */
  @Column('jsonb', { default: () => "'{}'" })
  metadata: {
    stylePreset?: string
    aspectRatio?: string
    avatarStyle?: string
    duration?: string
    background?: string
    artStyle?: string
    quality?: string
    templateId?: number
    [key: string]: any
  }

  /**
   * Performance metrics
   */
  @Column('jsonb', { nullable: true, default: () => "'{}'" })
  performance: {
    impressions?: number
    clicks?: number
    conversions?: number
    ctr?: number
    cpc?: number
    roas?: number
    lastUpdated?: Date
  }

  /**
   * Whether creative is active
   */
  @Column({ default: true })
  isActive: boolean

  /**
   * Collaboration: shared with other users
   */
  @Column('jsonb', { nullable: true, default: () => "'[]'" })
  sharedWith: Array<{
    userId: string
    permission: 'view' | 'edit' | 'admin'
    sharedAt: Date
  }>

  /**
   * Version control for iterations
   */
  @Column({ default: 1 })
  version: number

  /**
   * Parent creative ID (for versions)
   */
  @Column({ nullable: true })
  parentCreativeId: string

  /**
   * Tags for organization
   */
  @Column('jsonb', { nullable: true, default: () => "'[]'" })
  tags: string[]

  /**
   * Audit fields
   */
  @CreateDateColumn()
  createdAt: Date

  @UpdateDateColumn()
  updatedAt: Date
}
